language: cpp

sudo: required
dist: trusty

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq

install:
- sudo apt-get install -qq libqt4-dev libjack-dev libasound2-dev libsndfile1-dev
- sudo apt-get install -qq libvorbis-dev libmad0-dev libsamplerate-dev zlib1g-dev
- sudo apt-get install -qq ladspa-sdk dssi-dev liblo-dev librubberband-dev
- sudo apt-get install -qq lv2-dev liblilv-dev libsuil-dev

before_script:
- ./autogen.sh

script:
- ./configure --enable-qt4
  && make
  && sudo make install
